apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: {{ .Values.nginx.labels.app }}
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      nodePort: 30007

