apiVersion: batch/v1
kind: CronJob
metadata:
  name: ab
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ab
            image: jordi/ab
            imagePullPolicy: IfNotPresent
            command:
            - ab
            - -n 1000
            - -c 5
            - http://nginx-service/{{ .Values.nginx.port }}
          restartPolicy: OnFailure
